[package]
name = "logic-sim-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.8.0"
bincode = "0.9.2"

[dependencies.eframe]
version = "0.19.0"
features = ["serde"]

[dependencies.epaint]
version = "0.19.0"
features = ["serde"]

[dependencies.serde]
version = "^1"
features = ["serde_derive"]
