[package]
name = "logic-sim-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.8.0"
bincode = "0.9.2"
hashbrown = "0.12.3"
dirs = "4.0"
serde_json = "1.0"
rfd = "0.10"

[dependencies.eframe]
# version = "0.19.0"
git = "https://github.com/emilk/egui.git"

[dependencies.serde]
version = "^1"
features = ["serde_derive"]
