[package]
name = "logic-sim-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.19.0"
fastrand = "1.8.0"
bincode = "1.3.3"

[dependencies.serde]
version = "^1.0.0"

[dependencies.serde_derive]
version = "^1.0.0"
